// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7uODjicQ2LmFA7L5MQRcXnlbilPUM2CA',
    appId: '1:633810212439:web:81d7a2e57e3a21581b3512',
    messagingSenderId: '633810212439',
    projectId: 'fir-tutorial-5b87f',
    authDomain: 'fir-tutorial-5b87f.firebaseapp.com',
    storageBucket: 'fir-tutorial-5b87f.firebasestorage.app',
    measurementId: 'G-2YBJVM46KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr-FhFPcWVzToiyoSnEDXWnlWRmhIunFY',
    appId: '1:633810212439:android:71a820b7824eb6ef1b3512',
    messagingSenderId: '633810212439',
    projectId: 'fir-tutorial-5b87f',
    storageBucket: 'fir-tutorial-5b87f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAINSEcYAuQPRqzd3KKnBe2L8bfQfPKp2Y',
    appId: '1:633810212439:ios:1735e79e275c69001b3512',
    messagingSenderId: '633810212439',
    projectId: 'fir-tutorial-5b87f',
    storageBucket: 'fir-tutorial-5b87f.firebasestorage.app',
    androidClientId: '633810212439-b2c6gbkk6ngebia6ge3n5d9rsp1204lv.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAINSEcYAuQPRqzd3KKnBe2L8bfQfPKp2Y',
    appId: '1:633810212439:ios:1735e79e275c69001b3512',
    messagingSenderId: '633810212439',
    projectId: 'fir-tutorial-5b87f',
    storageBucket: 'fir-tutorial-5b87f.firebasestorage.app',
    androidClientId: '633810212439-b2c6gbkk6ngebia6ge3n5d9rsp1204lv.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7uODjicQ2LmFA7L5MQRcXnlbilPUM2CA',
    appId: '1:633810212439:web:0985c3a66da63e311b3512',
    messagingSenderId: '633810212439',
    projectId: 'fir-tutorial-5b87f',
    authDomain: 'fir-tutorial-5b87f.firebaseapp.com',
    storageBucket: 'fir-tutorial-5b87f.firebasestorage.app',
    measurementId: 'G-D8XJFLD92S',
  );
}
